# image: https://hub.docker.com/_/matomo
# docs: https://matomo.org/faq/on-premise/installing-matomo/


version: '3.8'

services:
  matomo:
    image: $APP_REPO:$APP_VERSION
    container_name: ${APP_NAME}
    ports:
      - '${APP_HTTP_PORT}:80'
    environment:
      - MATOMO_DATABASE_HOST=mysql
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=${DB_MYSQL_USER}
      - MATOMO_DATABASE_PASSWORD=${DB_MYSQL_PASSWORD}
      - MATOMO_DATABASE_DBNAME=${DB_MYSQL_NAME}
    volumes:
      - 'matomo:/var/www/html'
    depends_on:
      - mysql

  mysql:
    image: mysql:${DB_MYSQL_VERSION}
    container_name: ${APP_NAME}-db
    command: --default-authentication-plugin=mysql_native_password    
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    restart: always

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  mysql:
  matomo:
